### ISSUE TITLE
README.md の追加

### ISSUE THREAD

**Issue by go** [c-yano/mikanmikan#12]
現状、ゼロから動く環境用意しようと思うとちょっと大変なので以下を **README.md** として記載

- [ ] 環境要件
- [ ] インストール手順
- [ ] Web アクセス方法

**Comment by c-yano** [comment]
情報の統一のためWiKiにて記載

**Comment by c-yano** [comment]
テストコメント

**Comment by go** [comment]
**HTML** で記述されているので **Markdown** での記述に直してください

**Comment by go** [comment]
直っているのを確認したのでクローズ
