### ISSUE TITLE
MySQLの基本設定手順をWikiに記述する

### ISSUE THREAD

**Issue by isamukoseda** [c-yano/mikanmikan#13]

**Comment by go** [comment]
復習のため @Ryoukan を追加アサイン

**Comment by isamukoseda** [comment]
こんな感じかな？
足りない手順があればご指摘下さい

**Comment by s-akiko-s** [comment]
akikosugi:~/workspace $ mysql-ctl restart
 * Stopping MySQL database server mysqld
   ...done.
 * Starting MySQL database server mysqld
   ...fail!
akikosugi:~/workspace $

**Comment by s-akiko-s** [comment]
akikosugi:~/workspace $ mysql -f -u root -p < dump.sql
Enter password: 
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">



  <link ' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
      <tr>
        <td id="L11" class="blob-num js-line-number' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
      <tr>
        <td id="L13" class="blob-num js-line-number' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
      <tr>
        <td id="L14" class="blob-num js-line-number' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
      <tr>
        <td id="L15" class="blob-num js-line-number' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
      <tr>
        <td id="L20" class="blob-num js-line-number' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
      <tr>
        <td id="L24" class="blob-num js-line-number' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
      <tr>
        <td id="L36" class="blob-num js-line-number' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '</td>
      </tr>
</table>

  </div>

</div>

<button type="button" data-facebox' at line 1
ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2017 <span title="0.07211s from github-fe163-cp1-prd.iad.github.net">GitHub</spa' at line 1
akikosugi:~/workspace $ 
akikosugi:~/workspace $ 
akikosugi:~/workspace $ 
akikosugi:~/workspace $ show variables like "char%";
bash: show: command not found
akikosugi:~/workspace $ 
akikosugi:~/workspace $ 
akikosugi:~/workspace $ mysql-ctl cli
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 55
Server version: 5.5.54-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
mysql> show tables
    -> ;
ERROR 1046 (3D000): No database selected
mysql> show databacese;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'databacese' at line 1
mysql> show databaces;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'databaces' at line 1
mysql> 
mysql> 
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| c9                 |
| mysql              |
| performance_schema |
| phpmyadmin         |
+--------------------+
5 rows in set (0.00 sec)

mysql>

**Comment by isamukoseda** [comment]
手順を見直します

**Comment by isamukoseda** [comment]
isamukoseda:~/workspace (master) $ mysql -f -u root -p < dump.sql 
Enter password: 
ERROR 1049 (42000) at line 10: Unknown database 'Shop'
ERROR 1046 (3D000) at line 12: No database selected
ERROR 1046 (3D000) at line 13: No database selected
ERROR 1008 (HY000) at line 14: Can't drop database 'Shop'; database doesn't exist
isamukoseda:~/workspace (master) $ 

な感じでエラーがでますが、
isamukoseda:~/workspace (master) $ mysql-ctl cli
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| Shop               |
| c9                 |
| mysql              |
| performance_schema |
| phpmyadmin         |
+--------------------+
6 rows in set (0.00 sec)

mysql> 

な感じでShopデータベースが出来ているので、手順としては問題なさそうですが...
Wikiの手順で手を抜いた部分を少し追加します

**Comment by isamukoseda** [comment]
dump.sqlが古かったので、git pullで新しいdump.sqlファイルを入手していただければ（たぶん）問題なくセットアップは完了すると思います。
Wikiに新規セットアップのページを追加しておきましたので、確認してください

**Comment by s-akiko-s** [comment]
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| Shop               |
| c9                 |
| mysql              |
| performance_schema |
| phpmyadmin         |
+--------------------+
6 rows in set (0.00 sec)

databaseの作成できました！
ありがとうございます

**Comment by isamukoseda** [comment]
手順として大丈夫みたいなので、クロースしちゃいます
