### ISSUE TITLE
Databaseがちゃんと作れません

### ISSUE THREAD

**Issue by Ryoukan** [c-yano/mikanmikan#17]

**Comment by Ryoukan** [comment]
product_list.php を実行すると「ただいま障害により大変ご迷惑をお掛けしております 」の表示になります。これは、商品のDBがないために起こっています。外からDBを登録する特殊な方法ってどうやるのですか？今日教えてください。

**Comment by isamukoseda** [comment]
dump.sqlファイル中の以下のコードが新規インスタンスの場合にエラーとなるので、この部分を削除してから実行してください。
```
USE `Shop`;

DROP TABLE IF EXISTS `shop_product`;
DROP TABLE IF EXISTS `shop_staff`;
DROP DATABASE `Shop`;
```

**Comment by isamukoseda** [comment]
mysqlコマンドに-fオプションを指定することで、エラーを無視してくれるみたいなので、上記4行を削除しない場合には、-fオプション付きで実行すると最後まで処理が実行されます。
未検証なので、確認してWikiを更新しておきます

**Comment by isamukoseda** [comment]
Wikiに手順書を追加しておきました

**Comment by Ryoukan** [comment]
OKでした！！無事DBが導入されました！
