### ISSUE TITLE
[product] product_list.phpの画面表示処理をまとめましょう

### ISSUE THREAD

**Issue by isamukoseda** [c-yano/mikanmikan#2]
（具体的には、あとで書く）

**Comment by isamukoseda** [comment]
issue#2というbranchを作りましたので、これを参考にもう少し手を加えてみてもらえますか？

**Comment by go** [comment]
この issue って PR #22 に修正コード含まれてる?

**Comment by Ryoukan** [comment]
@go  はい。isuue #1の修正コードに含まれています。#1 では､DBアクセスの共通化と、HTMLヘッダの共通化をしています。

**Comment by Ryoukan** [comment]
issue #22 ってなんでしたっけ？issue #1 を間違えて上げちゃったやつですかね？

**Comment by go** [comment]
issue #1 と重複しているのでクローズ
