### ISSUE TITLE
ReadMeの変更お願いします！

### ISSUE THREAD

**Issue by Ryoukan** [c-yano/mikanmikan#25]
4の前 にgit pull origin masterでpull の指定を追加。

５番以下の順番が逆（cloud9の場合？）commit からのadd 。add の場合は commit時に出てきた、赤字ファイルを右クリックでadd
$ git add file-name // ステージングエリアにあげる
$ git commit -m "#番号 修正内容を簡潔に記入する" // コメント付きでコミットする例

pull request後に、marge requestが必要？？

**Comment by go** [comment]
コミット ae3e05758e4451d36fa43774882f269caa13087c で fix しているのを確認したのでクローズ
