### ISSUE TITLE
GUI 上でバックログが表示される

### ISSUE THREAD

**Issue by go** [c-yano/mikanmikan#28]
商品の修正などのオペレーション時にデバッグログが出力されているのを削除する

**Comment by c-yano** [comment]
デバックログ15ファイル修正しました。（見直し用として削除ではなく、コメントアウトさせていただきました。が、起動アプリのプログラムファイルには確認コマンドはコメントアウトでも残さないという認識はあるので、気になる場合は削除します。）

**Comment by go** [comment]
PR #29 の修正内容をマージしたのでクローズ
