### ISSUE TITLE
テスト用サンプルデータ

### ISSUE THREAD

**Issue by go** [c-yano/mikanmikan#5]
テスト向けにDBのサンプルデータを追加しておく必要がありますね

**Comment by c-yano** [comment]
了解です。いろいろ足りないなぁ～。
DBのアクセスパスワードとかそのままGitHubに掲載しちゃっているし・・。

**Comment by c-yano** [comment]
test

**Comment by go** [comment]
Issue #6 と重複しているのでクローズ

**Comment by isamukoseda** [comment]
多分、データとテーブル後続は別に提示してくれるらしいので、オープンしておきます
