### ISSUE TITLE
MySQLのテーブル定義ファイルを追加する

### ISSUE THREAD

**Issue by isamukoseda** [c-yano/mikanmikan#6]
最初に作成した、MySQLのテーブル構造（と共有するレコードがあれば）をdumpした結果をファイルとして共有する

**Comment by isamukoseda** [comment]
$ mysqldump -u root データベース名 > dump.sql
で、dump.sqlを少し整理してからgit addって感じだと思います

**Comment by c-yano** [comment]
mysql> mysqldump -u shopadmin Shop shop_product > dump.sql;                                 
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump -u shopadmin Shop shop_product > dump.sql' at line 1

**Comment by isamukoseda** [comment]
mysqldumpって無いのかなぁ〜@Cloud9

**Comment by isamukoseda** [comment]
isamukoseda:~/workspace (master) $ mysqldump ...
な感じで、shell上でお願いします

**Comment by isamukoseda** [comment]
$ mysqldump -u shopadmin -p Shop > shop.sql
で、Password聞かれるのでパスワードを入力すると、shop.sqlというファイルが作成されます。

**Comment by isamukoseda** [comment]
$ mysqldump -u shopadmin -p -B Shop > shop.sql
でした。ゴメンなさい。（Database定義がふくまれていませんでした）
